import { getPayload } from 'payload'
import config from '../../../payload.config'

type CurrencyEntry = {
  label: string
  symbol: string
  alpha2: string
  alpha3: string
}

export async function seedAllCurrencies() {
  const payload = await getPayload({ config })

  console.log('🌱 Starting full currency seed...')

  // If any currency exists, skip
  const existing = await payload.find({
    collection: 'currency',
    limit: 1,
  })
  if (existing.totalDocs > 0) {
    console.log('✅ Currencies already exist, skipping seed')
    return
  }

  const currencies: CurrencyEntry[] = [
    { label: 'Afghan Afghani', symbol: '؋', alpha2: 'AF', alpha3: 'AFN' },
    { label: 'Euro', symbol: '€', alpha2: 'EU', alpha3: 'EUR' },
    { label: 'Albanian Lek', symbol: 'L', alpha2: 'AL', alpha3: 'ALL' },
    { label: 'Armenian Dram', symbol: '֏', alpha2: 'AM', alpha3: 'AMD' },
    { label: 'Netherlands Antillean Guilder', symbol: 'ƒ', alpha2: 'AN', alpha3: 'ANG' },
    { label: 'Angolan Kwanza', symbol: 'Kz', alpha2: 'AO', alpha3: 'AOA' },
    { label: 'Argentine Peso', symbol: '$', alpha2: 'AR', alpha3: 'ARS' },
    { label: 'Australian Dollar', symbol: 'A$', alpha2: 'AU', alpha3: 'AUD' },
    { label: 'Aruban Florin', symbol: 'ƒ', alpha2: 'AW', alpha3: 'AWG' },
    { label: 'Azerbaijani Manat', symbol: '₼', alpha2: 'AZ', alpha3: 'AZN' },
    { label: 'Bosnia and Herzegovina Convertible Mark', symbol: 'KM', alpha2: 'BA', alpha3: 'BAM' },
    { label: 'Barbadian Dollar', symbol: '$', alpha2: 'BB', alpha3: 'BBD' },
    { label: 'Bangladeshi Taka', symbol: '৳', alpha2: 'BD', alpha3: 'BDT' },
    { label: 'Bulgarian Lev', symbol: 'лв', alpha2: 'BG', alpha3: 'BGN' },
    { label: 'Bahraini Dinar', symbol: '.د.ب', alpha2: 'BH', alpha3: 'BHD' },
    { label: 'Burundian Franc', symbol: 'FBu', alpha2: 'BI', alpha3: 'BIF' },
    { label: 'Bermudian Dollar', symbol: '$', alpha2: 'BM', alpha3: 'BMD' },
    { label: 'Brunei Dollar', symbol: '$', alpha2: 'BN', alpha3: 'BND' },
    { label: 'Boliviano', symbol: 'Bs.', alpha2: 'BO', alpha3: 'BOB' },
    { label: 'Brazilian Real', symbol: 'R$', alpha2: 'BR', alpha3: 'BRL' },
    { label: 'Bahamian Dollar', symbol: '$', alpha2: 'BS', alpha3: 'BSD' },
    { label: 'Bhutanese Ngultrum', symbol: 'Nu.', alpha2: 'BT', alpha3: 'BTN' },
    { label: 'Botswana Pula', symbol: 'P', alpha2: 'BW', alpha3: 'BWP' },
    { label: 'Belarusian Ruble', symbol: 'Br', alpha2: 'BY', alpha3: 'BYN' },
    { label: 'Belize Dollar', symbol: '$', alpha2: 'BZ', alpha3: 'BZD' },
    { label: 'Canadian Dollar', symbol: 'C$', alpha2: 'CA', alpha3: 'CAD' },
    { label: 'Congolese Franc', symbol: 'FC', alpha2: 'CD', alpha3: 'CDF' },
    { label: 'Swiss Franc', symbol: 'CHF', alpha2: 'CH', alpha3: 'CHF' },
    { label: 'Chilean Peso', symbol: '$', alpha2: 'CL', alpha3: 'CLP' },
    { label: 'Chinese Yuan', symbol: '¥', alpha2: 'CN', alpha3: 'CNY' },
    { label: 'Colombian Peso', symbol: '$', alpha2: 'CO', alpha3: 'COP' },
    { label: 'Costa Rican Colón', symbol: '₡', alpha2: 'CR', alpha3: 'CRC' },
    { label: 'Cuban Peso', symbol: '$', alpha2: 'CU', alpha3: 'CUP' },
    { label: 'Cape Verde Escudo', symbol: '$', alpha2: 'CV', alpha3: 'CVE' },
    { label: 'Czech Koruna', symbol: 'Kč', alpha2: 'CZ', alpha3: 'CZK' },
    { label: 'Djiboutian Franc', symbol: 'Fdj', alpha2: 'DJ', alpha3: 'DJF' },
    { label: 'Danish Krone', symbol: 'kr', alpha2: 'DK', alpha3: 'DKK' },
    { label: 'Dominican Peso', symbol: 'RD$', alpha2: 'DO', alpha3: 'DOP' },
    { label: 'Algerian Dinar', symbol: 'د.ج', alpha2: 'DZ', alpha3: 'DZD' },
    { label: 'Egyptian Pound', symbol: '£', alpha2: 'EG', alpha3: 'EGP' },
    { label: 'Eritrean Nakfa', symbol: 'Nfk', alpha2: 'ER', alpha3: 'ERN' },
    { label: 'Ethiopian Birr', symbol: 'Br', alpha2: 'ET', alpha3: 'ETB' },
    { label: 'Fijian Dollar', symbol: '$', alpha2: 'FJ', alpha3: 'FJD' },
    { label: 'Falkland Islands Pound', symbol: '£', alpha2: 'FK', alpha3: 'FKP' },
    { label: 'Pound Sterling', symbol: '£', alpha2: 'GB', alpha3: 'GBP' },
    { label: 'Georgian Lari', symbol: '₾', alpha2: 'GE', alpha3: 'GEL' },
    { label: 'Ghanaian Cedi', symbol: '₵', alpha2: 'GH', alpha3: 'GHS' },
    { label: 'Gibraltar Pound', symbol: '£', alpha2: 'GI', alpha3: 'GIP' },
    { label: 'Gambian Dalasi', symbol: 'D', alpha2: 'GM', alpha3: 'GMD' },
    { label: 'Guinean Franc', symbol: 'FG', alpha2: 'GN', alpha3: 'GNF' },
    { label: 'Guatemalan Quetzal', symbol: 'Q', alpha2: 'GT', alpha3: 'GTQ' },
    { label: 'Guyanese Dollar', symbol: '$', alpha2: 'GY', alpha3: 'GYD' },
    { label: 'Hong Kong Dollar', symbol: 'HK$', alpha2: 'HK', alpha3: 'HKD' },
    { label: 'Honduran Lempira', symbol: 'L', alpha2: 'HN', alpha3: 'HNL' },
    { label: 'Croatian Kuna', symbol: 'kn', alpha2: 'HR', alpha3: 'HRK' },
    { label: 'Haitian Gourde', symbol: 'G', alpha2: 'HT', alpha3: 'HTG' },
    { label: 'Hungarian Forint', symbol: 'Ft', alpha2: 'HU', alpha3: 'HUF' },
    { label: 'Indonesian Rupiah', symbol: 'Rp', alpha2: 'ID', alpha3: 'IDR' },
    { label: 'Israeli New Shekel', symbol: '₪', alpha2: 'IL', alpha3: 'ILS' },
    { label: 'Indian Rupee', symbol: '₹', alpha2: 'IN', alpha3: 'INR' },
    { label: 'Iraqi Dinar', symbol: 'ع.د', alpha2: 'IQ', alpha3: 'IQD' },
    { label: 'Iranian Rial', symbol: '﷼', alpha2: 'IR', alpha3: 'IRR' },
    { label: 'Icelandic Króna', symbol: 'kr', alpha2: 'IS', alpha3: 'ISK' },
    { label: 'Jamaican Dollar', symbol: '$', alpha2: 'JM', alpha3: 'JMD' },
    { label: 'Jordanian Dinar', symbol: 'JD', alpha2: 'JO', alpha3: 'JOD' },
    { label: 'Kenyan Shilling', symbol: 'KSh', alpha2: 'KE', alpha3: 'KES' },
    { label: 'Kyrgyzstani Som', symbol: 'сом', alpha2: 'KG', alpha3: 'KGS' },
    { label: 'Cambodian Riel', symbol: '៛', alpha2: 'KH', alpha3: 'KHR' },
    { label: 'Comorian Franc', symbol: 'CF', alpha2: 'KM', alpha3: 'KMF' },
    { label: 'North Korean Won', symbol: '₩', alpha2: 'KP', alpha3: 'KPW' },
    { label: 'South Korean Won', symbol: '₩', alpha2: 'KR', alpha3: 'KRW' },
    { label: 'Kuwaiti Dinar', symbol: 'د.ك', alpha2: 'KW', alpha3: 'KWD' },
    { label: 'Cayman Islands Dollar', symbol: '$', alpha2: 'KY', alpha3: 'KYD' },
    { label: 'Kazakhstani Tenge', symbol: '₸', alpha2: 'KZ', alpha3: 'KZT' },
    { label: 'Lao Kip', symbol: '₭', alpha2: 'LA', alpha3: 'LAK' },
    { label: 'Lebanese Pound', symbol: 'ل.ل', alpha2: 'LB', alpha3: 'LBP' },
    { label: 'Sri Lankan Rupee', symbol: 'රු', alpha2: 'LK', alpha3: 'LKR' },
    { label: 'Lesotho Loti', symbol: 'L', alpha2: 'LS', alpha3: 'LSL' },
    { label: 'Libyan Dinar', symbol: 'ل.د', alpha2: 'LY', alpha3: 'LYD' },
    { label: 'Moroccan Dirham', symbol: 'د.م.', alpha2: 'MA', alpha3: 'MAD' },
    { label: 'Moldovan Leu', symbol: 'L', alpha2: 'MD', alpha3: 'MDL' },
    { label: 'Malagasy Ariary', symbol: 'Ar', alpha2: 'MG', alpha3: 'MGA' },
    { label: 'Macedonian Denar', symbol: 'ден', alpha2: 'MK', alpha3: 'MKD' },
    { label: 'Myanmar Kyat', symbol: 'Ks', alpha2: 'MM', alpha3: 'MMK' },
    { label: 'Mongolian Tugrik', symbol: '₮', alpha2: 'MN', alpha3: 'MNT' },
    { label: 'Macanese Pataca', symbol: 'P', alpha2: 'MO', alpha3: 'MOP' },
    { label: 'Mauritanian Ouguiya', symbol: 'UM', alpha2: 'MR', alpha3: 'MRU' },
    { label: 'Mauritian Rupee', symbol: '₨', alpha2: 'MU', alpha3: 'MUR' },
    { label: 'Maldivian Rufiyaa', symbol: 'Rf', alpha2: 'MV', alpha3: 'MVR' },
    { label: 'Malawian Kwacha', symbol: 'MK', alpha2: 'MW', alpha3: 'MWK' },
    { label: 'Mexican Peso', symbol: '$', alpha2: 'MX', alpha3: 'MXN' },
    { label: 'Malaysian Ringgit', symbol: 'RM', alpha2: 'MY', alpha3: 'MYR' },
    { label: 'Mozambican Metical', symbol: 'MT', alpha2: 'MZ', alpha3: 'MZN' },
    { label: 'Namibian Dollar', symbol: '$', alpha2: 'NA', alpha3: 'NAD' },
    { label: 'Nigerian Naira', symbol: '₦', alpha2: 'NG', alpha3: 'NGN' },
    { label: 'Nicaraguan Córdoba', symbol: 'C$', alpha2: 'NI', alpha3: 'NIO' },
    { label: 'Norwegian Krone', symbol: 'kr', alpha2: 'NO', alpha3: 'NOK' },
    { label: 'Nepalese Rupee', symbol: '₨', alpha2: 'NP', alpha3: 'NPR' },
    { label: 'New Zealand Dollar', symbol: '$', alpha2: 'NZ', alpha3: 'NZD' },
    { label: 'Omani Rial', symbol: 'ر.ع', alpha2: 'OM', alpha3: 'OMR' },
    { label: 'Panamanian Balboa', symbol: 'B/.', alpha2: 'PA', alpha3: 'PAB' },
    { label: 'Peruvian Sol', symbol: 'S/.', alpha2: 'PE', alpha3: 'PEN' },
    { label: 'Papua New Guinean Kina', symbol: 'K', alpha2: 'PG', alpha3: 'PGK' },
    { label: 'Philippine Peso', symbol: '₱', alpha2: 'PH', alpha3: 'PHP' },
    { label: 'Pakistani Rupee', symbol: '₨', alpha2: 'PK', alpha3: 'PKR' },
    { label: 'Polish Zloty', symbol: 'zł', alpha2: 'PL', alpha3: 'PLN' },
    { label: 'Paraguayan Guarani', symbol: '₲', alpha2: 'PY', alpha3: 'PYG' },
    { label: 'Qatari Rial', symbol: 'ر.ق', alpha2: 'QA', alpha3: 'QAR' },
    { label: 'Romanian Leu', symbol: 'lei', alpha2: 'RO', alpha3: 'RON' },
    { label: 'Serbian Dinar', symbol: 'дин', alpha2: 'RS', alpha3: 'RSD' },
    { label: 'Russian Ruble', symbol: '₽', alpha2: 'RU', alpha3: 'RUB' },
    { label: 'Rwandan Franc', symbol: 'FRw', alpha2: 'RW', alpha3: 'RWF' },
    { label: 'Saudi Riyal', symbol: '﷼', alpha2: 'SA', alpha3: 'SAR' },
    { label: 'Solomon Islands Dollar', symbol: '$', alpha2: 'SB', alpha3: 'SBD' },
    { label: 'Seychellois Rupee', symbol: '₨', alpha2: 'SC', alpha3: 'SCR' },
    { label: 'Sierra Leonean Leone', symbol: 'Le', alpha2: 'SL', alpha3: 'SLL' },
    { label: 'Somali Shilling', symbol: 'Sh', alpha2: 'SO', alpha3: 'SOS' },
    { label: 'Surinamese Dollar', symbol: '$', alpha2: 'SR', alpha3: 'SRD' },
    { label: 'South Sudanese Pound', symbol: '£', alpha2: 'SS', alpha3: 'SSP' },
    { label: 'São Tomé and Príncipe Dobra', symbol: 'Db', alpha2: 'ST', alpha3: 'STN' },
    { label: 'El Salvador Colón', symbol: '₡', alpha2: 'SV', alpha3: 'SVC' },
    { label: 'Syrian Pound', symbol: '£S', alpha2: 'SY', alpha3: 'SYP' },
    { label: 'Swazi Lilangeni', symbol: 'L', alpha2: 'SZ', alpha3: 'SZL' },
    { label: 'Thai Baht', symbol: '฿', alpha2: 'TH', alpha3: 'THB' },
    { label: 'Tajikistani Somoni', symbol: 'ЅМ', alpha2: 'TJ', alpha3: 'TJS' },
    { label: 'Turkmenistan Manat', symbol: 'm', alpha2: 'TM', alpha3: 'TMT' },
    { label: 'Tunisian Dinar', symbol: 'د.ت', alpha2: 'TN', alpha3: 'TND' },
    { label: 'Tongan Paʻanga', symbol: 'T$', alpha2: 'TO', alpha3: 'TOP' },
    { label: 'Turkish Lira', symbol: '₺', alpha2: 'TR', alpha3: 'TRY' },
    { label: 'Trinidad & Tobago Dollar', symbol: '$', alpha2: 'TT', alpha3: 'TTD' },
    { label: 'Taiwan Dollar', symbol: 'NT$', alpha2: 'TW', alpha3: 'TWD' },
    { label: 'Tanzanian Shilling', symbol: 'TSh', alpha2: 'TZ', alpha3: 'TZS' },
    { label: 'Ukrainian Hryvnia', symbol: '₴', alpha2: 'UA', alpha3: 'UAH' },
    { label: 'Ugandan Shilling', symbol: 'USh', alpha2: 'UG', alpha3: 'UGX' },
    { label: 'US Dollar', symbol: '$', alpha2: 'US', alpha3: 'USD' },
    { label: 'Uruguayan Peso', symbol: '$U', alpha2: 'UY', alpha3: 'UYU' },
    { label: 'Uzbekistan Som', symbol: 'лв', alpha2: 'UZ', alpha3: 'UZS' },
    { label: 'Venezuelan Bolívar Soberano', symbol: 'Bs.S', alpha2: 'VE', alpha3: 'VES' },
    { label: 'Vietnamese Dong', symbol: '₫', alpha2: 'VN', alpha3: 'VND' },
    { label: 'Vanuatu Vatu', symbol: 'Vt', alpha2: 'VU', alpha3: 'VUV' },
    { label: 'Samoan Tala', symbol: 'T$', alpha2: 'WS', alpha3: 'WST' },
    { label: 'CFA Franc BEAC', symbol: 'FCFA', alpha2: 'CM', alpha3: 'XAF' },
    { label: 'East Caribbean Dollar', symbol: '$', alpha2: 'AG', alpha3: 'XCD' },
    { label: 'Special Drawing Rights', symbol: 'SDR', alpha2: 'XX', alpha3: 'XDR' },
    { label: 'CFA Franc BCEAO', symbol: 'CFA', alpha2: 'SN', alpha3: 'XOF' },
    { label: 'CFP Franc', symbol: '₣', alpha2: 'PF', alpha3: 'XPF' },
    { label: 'Yemeni Rial', symbol: '﷼', alpha2: 'YE', alpha3: 'YER' },
    { label: 'South African Rand', symbol: 'R', alpha2: 'ZA', alpha3: 'ZAR' },
    { label: 'Zambian Kwacha', symbol: 'ZK', alpha2: 'ZM', alpha3: 'ZMW' },
  ]

  for (const cur of currencies) {
    await payload.create({
      collection: 'currency',
      data: cur,
    })
  }

  console.log('✅ All currencies seeded')
}
